repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.31.7
    hooks:
      - id: basedpyright
  - repo: local
    hooks:
      - id: test
        name: run tests
        entry: scripts/run test
        language: script
        types: [python]
        pass_filenames: false
