from typing import Literal, overload

def load_translations() -> None: ...
def _(message: str) -> str: ...
def ngettext(single: str, plural: str, count: int) -> str: ...
@overload
def get_resources(name: str) -> bytes: ...
@overload
def get_resources(list_of_names: list[str]) -> dict[str, bytes]: ...
@overload
def get_path(path: str) -> str: ...
@overload
def get_path(path: str, data: Literal[False]) -> str: ...
@overload
def get_path(path: str, data: Literal[True]) -> bytes: ...
@overload
def get_image_path(path: str) -> str: ...
@overload
def get_image_path(path: str, data: Literal[False]) -> str: ...
@overload
def get_image_path(path: str, data: Literal[True]) -> bytes: ...

I = get_image_path
P = get_path
