---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: CI

# Controls when the action will run. Workflow runs when manually triggered
# using the UI or API.
"on":
  push:
    branches:
      - "*"
  pull_request:

permissions: {}

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - uses: actions/checkout@v4
        with:
          repository: kovidgoyal/calibre
          path: "calibre-repo"
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1

      - name: Install Python
        # Install both the project version and >=3.11 for prek envs
        run: |
          uv python install
          uv python install '>=3.11'

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install Calibre dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libegl1 libopengl0 libxkbcommon0

      - name: Cache minimum Calibre package
        uses: actions/cache@v4
        with:
          key: calibre-v5.13.0
          path: calibre-v5.13.0

      - uses: j178/prek-action@91fd7d7cf70ae1dee9f4f44e7dfa5d1073fe6623 # v1.0.11
