---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: CI

# Controls when the action will run. Workflow runs when manually triggered
# using the UI or API.
"on":
  push:
    branches:
      - "*"
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/checkout@v4
        with:
          repository: kovidgoyal/calibre
          path: "calibre-repo"
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - uses: astral-sh/ruff-action@v3
      - run: ruff check
      - run: ruff format --check

      - run: uv tool install basedpyright
      - run: basedpyright

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libegl1 libopengl0 libxkbcommon0

      - name: Cache minimum Calibre package
        uses: actions/cache@v4
        with:
          key: calibre-v5.13.0
          path: calibre-v5.13.0

      - name: Run tests
        run: ./scripts/run test
