---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Create release

'on':
  push:
    tags:
      - 'v*'

jobs:
  upload-assets:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Check out release tag
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build ZIP file
        run: ./scripts/run build

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: 'KoboUtilities-*.zip'
